"""catalog and config tables

Revision ID: 3a040f953e87
Revises: f6c8548cd521
Create Date: 2026-08-24 23:23:01.536830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a040f953e87'
down_revision: Union[str, Sequence[str], None] = 'f6c8548cd521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS platform")
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ENABLED', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    schema='knowledge',
    comment='文档类型'
    )
    op.create_index('uq_document_types_code', 'document_types', ['code'], unique=True, schema='knowledge')
    op.create_table('product_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ENABLED', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_forms')),
    schema='knowledge',
    comment='产品形态'
    )
    op.create_index('uq_product_forms_code', 'product_forms', ['code'], unique=True, schema='knowledge')
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ENABLED', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    schema='knowledge',
    comment='产品'
    )
    op.create_index('uq_products_code', 'products', ['code'], unique=True, schema='knowledge')
    op.create_table('source_priorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ENABLED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_priorities')),
    schema='knowledge',
    comment='来源优先级'
    )
    op.create_index('uq_source_priorities_priority', 'source_priorities', ['priority'], unique=True, schema='knowledge')
    op.create_index('uq_source_priorities_source_code', 'source_priorities', ['source_code'], unique=True, schema='knowledge')
    op.create_table('secret_values',
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'key_name', name=op.f('pk_secret_values')),
    schema='platform',
    comment='配置密钥密文'
    )
    op.create_index('uq_secret_values_ns_key', 'secret_values', ['namespace', 'key_name'], unique=True, schema='platform')
    op.create_table('product_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version_code', sa.String(length=128), nullable=False),
    sa.Column('major_version', sa.Integer(), nullable=True),
    sa.Column('minor_version', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ENABLED', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['knowledge.products.id'], name=op.f('fk_product_versions_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_versions')),
    schema='knowledge',
    comment='产品版本'
    )
    op.create_index('uq_product_versions_product_code', 'product_versions', ['product_id', 'version_code'], unique=True, schema='knowledge')
    op.create_table('config_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth.users.id'], name=op.f('fk_config_revisions_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_revisions')),
    schema='platform',
    comment='配置版本'
    )
    op.create_index('uq_active_config_namespace', 'config_revisions', ['namespace'], unique=True, schema='platform', postgresql_where=sa.text("status = 'ACTIVE'"))

    # 目录 seed（版本化初始化，应用不静默改表结构）
    op.execute("""
        INSERT INTO knowledge.products (id, code, name, status, sort_order) VALUES
          ('00000000-0000-0000-0000-000000000010', 'ae-gateway', 'AE 安全网关', 'ENABLED', 10),
          ('00000000-0000-0000-0000-000000000020', 'ae-management', 'AE 管理系统', 'ENABLED', 20);
        INSERT INTO knowledge.product_versions (id, product_id, version_code, major_version, minor_version, status, sort_order) VALUES
          ('00000000-0000-0000-0000-000000000011', '00000000-0000-0000-0000-000000000010', '1.0', 1, 0, 'ENABLED', 10),
          ('00000000-0000-0000-0000-000000000021', '00000000-0000-0000-0000-000000000020', '2.1', 2, 1, 'ENABLED', 10);
        INSERT INTO knowledge.document_types (id, code, name, description, status, sort_order) VALUES
          ('00000000-0000-0000-0000-000000000031', 'requirement', '需求说明书', NULL, 'ENABLED', 10),
          ('00000000-0000-0000-0000-000000000032', 'design', '设计文档', NULL, 'ENABLED', 20),
          ('00000000-0000-0000-0000-000000000033', 'fault-analysis', '故障分析', NULL, 'ENABLED', 30),
          ('00000000-0000-0000-0000-000000000034', 'test-report', '测试报告', NULL, 'ENABLED', 40),
          ('00000000-0000-0000-0000-000000000035', 'manual', '操作手册', NULL, 'ENABLED', 50);
        INSERT INTO knowledge.product_forms (id, code, name, status, sort_order) VALUES
          ('00000000-0000-0000-0000-000000000041', 'mainline', '主线', 'ENABLED', 10),
          ('00000000-0000-0000-0000-000000000042', 'domestic', '国产化', 'ENABLED', 20),
          ('00000000-0000-0000-0000-000000000043', 'custom', '定制', 'ENABLED', 30);
        INSERT INTO knowledge.source_priorities (id, source_code, display_name, priority, status) VALUES
          ('00000000-0000-0000-0000-000000000051', 'MANUAL_UPLOAD', '手工上传', 10, 'ENABLED'),
          ('00000000-0000-0000-0000-000000000052', 'FEISHU_WIKI', '飞书知识库', 20, 'ENABLED'),
          ('00000000-0000-0000-0000-000000000053', 'FEISHU_DOC', '飞书文档', 30, 'ENABLED'),
          ('00000000-0000-0000-0000-000000000054', 'SEG_CASE', 'SEG 问题案件', 40, 'ENABLED');
        INSERT INTO platform.config_revisions (namespace, content, status) VALUES
          ('llm', '{"provider": "openai-compatible", "base_url": "", "model": "", "temperature": 0.2, "top_p": 1.0, "max_tokens": 2048, "timeout_seconds": 60, "classification_model": "", "embedding_model": "", "enabled": false}', 'ACTIVE');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_config_namespace', table_name='config_revisions', schema='platform', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('config_revisions', schema='platform')
    op.drop_index('uq_product_versions_product_code', table_name='product_versions', schema='knowledge')
    op.drop_table('product_versions', schema='knowledge')
    op.drop_index('uq_secret_values_ns_key', table_name='secret_values', schema='platform')
    op.drop_table('secret_values', schema='platform')
    op.drop_index('uq_source_priorities_source_code', table_name='source_priorities', schema='knowledge')
    op.drop_index('uq_source_priorities_priority', table_name='source_priorities', schema='knowledge')
    op.drop_table('source_priorities', schema='knowledge')
    op.drop_index('uq_products_code', table_name='products', schema='knowledge')
    op.drop_table('products', schema='knowledge')
    op.drop_index('uq_product_forms_code', table_name='product_forms', schema='knowledge')
    op.drop_table('product_forms', schema='knowledge')
    op.drop_index('uq_document_types_code', table_name='document_types', schema='knowledge')
    op.drop_table('document_types', schema='knowledge')
    op.execute("DROP SCHEMA IF EXISTS platform")
    # ### end Alembic commands ###
