"""initial schema

Revision ID: c301e374b353
Revises: 
Create Date: 2026-08-24 15:11:49.888873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c301e374b353'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 逻辑 Schema（DD-03 §3）
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS knowledge")
    op.execute("CREATE SCHEMA IF NOT EXISTS tasking")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_source', sa.String(length=32), server_default='ADMIN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='auth',
    comment='系统用户'
    )
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True, schema='auth', postgresql_where=sa.text('username IS NOT NULL'))
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PROCESSING', nullable=False),
    sa.Column('update_status', sa.String(length=32), server_default='IDLE', nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('pending_version_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('offlined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_reason', sa.Text(), nullable=True),
    sa.Column('last_sync_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error_code', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth.users.id'], name=op.f('fk_knowledge_sources_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources')),
    schema='knowledge',
    comment='知识来源'
    )
    op.create_index('ix_knowledge_sources_owner_status', 'knowledge_sources', ['owner_user_id', 'status', 'updated_at'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_sources_status_update', 'knowledge_sources', ['status', 'update_status'], unique=False, schema='knowledge')
    op.create_index('uq_active_source_key', 'knowledge_sources', ['source_type', 'canonical_key'], unique=True, schema='knowledge', postgresql_where=sa.text("status <> 'OFFLINE'"))
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('external_revision', sa.String(length=128), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='CREATED', nullable=False),
    sa.Column('processing_stage', sa.String(length=32), nullable=True),
    sa.Column('raw_object_key', sa.Text(), nullable=True),
    sa.Column('parsed_object_key', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('parser_name', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('classification_config_revision', sa.BigInteger(), nullable=True),
    sa.Column('embedding_model_key', sa.String(length=128), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('index_generation', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge.knowledge_sources.id'], name=op.f('fk_document_versions_source_id_knowledge_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    schema='knowledge',
    comment='文档版本'
    )
    op.create_index('ix_document_versions_source_status', 'document_versions', ['source_id', 'status'], unique=False, schema='knowledge')
    op.create_index('uq_document_versions_source_version', 'document_versions', ['source_id', 'version_no'], unique=True, schema='knowledge')
    # 环形外键：knowledge_sources ↔ document_versions，两表建齐后再追加
    op.create_foreign_key(
        'fk_knowledge_sources_current_version_id_document_versions',
        'knowledge_sources', 'document_versions',
        ['current_version_id'], ['id'],
        source_schema='knowledge', referent_schema='knowledge',
    )
    op.create_foreign_key(
        'fk_knowledge_sources_pending_version_id_document_versions',
        'knowledge_sources', 'document_versions',
        ['pending_version_id'], ['id'],
        source_schema='knowledge', referent_schema='knowledge',
    )
    op.create_table('feishu_source_details',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_token', sa.String(length=256), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('space_id', sa.String(length=128), nullable=True),
    sa.Column('node_token', sa.String(length=256), nullable=True),
    sa.Column('last_seen_revision', sa.String(length=128), nullable=True),
    sa.Column('last_seen_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge.knowledge_sources.id'], name=op.f('fk_feishu_source_details_source_id_knowledge_sources')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_feishu_source_details')),
    schema='knowledge',
    comment='飞书来源详情'
    )
    op.create_table('processing_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('100'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=32), nullable=True),
    sa.Column('last_error_code', sa.String(length=128), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth.users.id'], name=op.f('fk_processing_tasks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasking.processing_tasks.id'], name=op.f('fk_processing_tasks_parent_task_id_processing_tasks')),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge.knowledge_sources.id'], name=op.f('fk_processing_tasks_source_id_knowledge_sources')),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge.document_versions.id'], name=op.f('fk_processing_tasks_version_id_document_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_tasks')),
    schema='tasking',
    comment='处理任务'
    )
    op.create_index('ix_task_claim', 'processing_tasks', ['priority', 'scheduled_at', 'created_at'], unique=False, schema='tasking', postgresql_where=sa.text("status IN ('PENDING', 'RETRY_WAIT')"))
    op.create_index('ix_tasks_source', 'processing_tasks', ['source_id'], unique=False, schema='tasking')
    op.create_index('ix_tasks_version', 'processing_tasks', ['version_id'], unique=False, schema='tasking')
    op.create_index('uq_open_task_idempotency', 'processing_tasks', ['idempotency_key'], unique=True, schema='tasking', postgresql_where=sa.text("status IN ('PENDING', 'RUNNING', 'RETRY_WAIT')"))
    op.create_table('task_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasking.processing_tasks.id'], name=op.f('fk_task_attempts_task_id_processing_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_attempts')),
    schema='tasking',
    comment='任务执行尝试'
    )
    op.create_index('uq_task_attempts_task_no', 'task_attempts', ['task_id', 'attempt_no'], unique=True, schema='tasking')

    # 种子数据：登录未实现前，来源归属的系统默认用户（与应用配置 default_owner_user_id 一致）
    op.execute(
        "INSERT INTO auth.users (id, username, display_name, status, is_admin, created_source) "
        "VALUES ('11111111-1111-1111-1111-111111111111', 'system', '系统', 'ACTIVE', false, 'ADMIN') "
        "ON CONFLICT (id) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除环形外键，再删表
    op.drop_constraint(
        'fk_knowledge_sources_pending_version_id_document_versions',
        'knowledge_sources', type_='foreignkey', schema='knowledge',
    )
    op.drop_constraint(
        'fk_knowledge_sources_current_version_id_document_versions',
        'knowledge_sources', type_='foreignkey', schema='knowledge',
    )
    op.drop_index('uq_task_attempts_task_no', table_name='task_attempts', schema='tasking')
    op.drop_table('task_attempts', schema='tasking')
    op.drop_index('uq_open_task_idempotency', table_name='processing_tasks', schema='tasking', postgresql_where=sa.text("status IN ('PENDING', 'RUNNING', 'RETRY_WAIT')"))
    op.drop_index('ix_tasks_version', table_name='processing_tasks', schema='tasking')
    op.drop_index('ix_tasks_source', table_name='processing_tasks', schema='tasking')
    op.drop_index('ix_task_claim', table_name='processing_tasks', schema='tasking', postgresql_where=sa.text("status IN ('PENDING', 'RETRY_WAIT')"))
    op.drop_table('processing_tasks', schema='tasking')
    op.drop_table('feishu_source_details', schema='knowledge')
    op.drop_index('uq_document_versions_source_version', table_name='document_versions', schema='knowledge')
    op.drop_index('ix_document_versions_source_status', table_name='document_versions', schema='knowledge')
    op.drop_table('document_versions', schema='knowledge')
    op.drop_index('uq_active_source_key', table_name='knowledge_sources', schema='knowledge', postgresql_where=sa.text("status <> 'OFFLINE'"))
    op.drop_index('ix_knowledge_sources_status_update', table_name='knowledge_sources', schema='knowledge')
    op.drop_index('ix_knowledge_sources_owner_status', table_name='knowledge_sources', schema='knowledge')
    op.drop_table('knowledge_sources', schema='knowledge')
    op.drop_index('uq_users_username_lower', table_name='users', schema='auth', postgresql_where=sa.text('username IS NOT NULL'))
    op.drop_table('users', schema='auth')
    op.execute("DROP SCHEMA IF EXISTS tasking")
    op.execute("DROP SCHEMA IF EXISTS knowledge")
    op.execute("DROP SCHEMA IF EXISTS auth")
    # ### end Alembic commands ###
