"""auth oauth identity sessions

Revision ID: f6c8548cd521
Revises: c301e374b353
Create Date: 2026-08-24 16:39:11.189529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6c8548cd521'
down_revision: Union[str, Sequence[str], None] = 'c301e374b353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    schema='auth',
    comment='飞书 OAuth state'
    )
    op.create_index('uq_oauth_states_state', 'oauth_states', ['state'], unique=True, schema='auth')
    op.create_table('external_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('tenant_key', sa.String(length=128), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=False),
    sa.Column('open_id', sa.String(length=128), nullable=True),
    sa.Column('union_id', sa.String(length=128), nullable=True),
    sa.Column('binding_status', sa.String(length=32), server_default='BOUND', nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_external_identities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identities')),
    schema='auth',
    comment='外部身份绑定'
    )
    op.create_index('ix_external_identities_user', 'external_identities', ['user_id'], unique=False, schema='auth')
    op.create_index('uq_external_identity_provider_tenant_user', 'external_identities', ['provider', 'tenant_key', 'external_user_id'], unique=True, schema='auth')
    op.create_table('login_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_login_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_login_sessions_token_hash')),
    schema='auth',
    comment='登录会话'
    )
    op.create_index('ix_login_sessions_user_expires', 'login_sessions', ['user_id', 'expires_at'], unique=False, schema='auth')
    op.create_table('external_credentials',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('access_token_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('key_version', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['auth.external_identities.id'], name=op.f('fk_external_credentials_identity_id_external_identities')),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_external_credentials')),
    schema='auth',
    comment='外部访问凭据（密文）'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_credentials', schema='auth')
    op.drop_index('ix_login_sessions_user_expires', table_name='login_sessions', schema='auth')
    op.drop_table('login_sessions', schema='auth')
    op.drop_index('uq_external_identity_provider_tenant_user', table_name='external_identities', schema='auth')
    op.drop_index('ix_external_identities_user', table_name='external_identities', schema='auth')
    op.drop_table('external_identities', schema='auth')
    op.drop_index('uq_oauth_states_state', table_name='oauth_states', schema='auth')
    op.drop_table('oauth_states', schema='auth')
    # ### end Alembic commands ###
