import { useEffect, useState } from "react";
import { Alert, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import { getErrorMessage } from "../../api/client";
import { getAdminUser, listAdminUsers, updateAdminUser, type AdminUser, type AdminUserDetail } from "../../api/adminUsers";
import { PageHeader } from "../../components/PageHeader";
import { useAuth } from "../../auth/AuthContext";

export function UsersPage() {
  const { user: currentUser } = useAuth();
  const [items, setItems] = useState<AdminUser[]>([]); const [error, setError] = useState<unknown>(null);
  const [detail, setDetail] = useState<AdminUserDetail | null>(null);
  const load = () => listAdminUsers().then(d => setItems(d.items)).catch(setError);
  useEffect(() => { void load(); }, []);
  const toggle = async (u: AdminUser) => { try { const next = await updateAdminUser(u.id, { status: u.status === "ACTIVE" ? "DISABLED" : "ACTIVE" }); setItems(xs => xs.map(x => x.id === u.id ? next : x)); } catch (e) { setError(e); } };
  return <><PageHeader title="用户管理" description="查看用户、角色与账号状态。管理员可启用或禁用账号。" actions={<Button variant="outlined" onClick={load}>刷新</Button>} />{error && <Alert severity="error" sx={{ mb: 2 }}>{getErrorMessage(error)}</Alert>}<Card><CardContent><Table size="small"><TableHead><TableRow><TableCell>用户</TableCell><TableCell>飞书账号 ID</TableCell><TableCell>角色</TableCell><TableCell>状态</TableCell><TableCell>操作</TableCell></TableRow></TableHead><TableBody>{items.map(u => { const protectedAccount = u.created_source === "SYSTEM" || u.id === currentUser?.id; return <TableRow key={u.id} hover onClick={() => void getAdminUser(u.id).then(setDetail).catch(setError)} sx={{ cursor: "pointer" }}><TableCell><Typography fontWeight={600}>{u.display_name}</Typography><Typography variant="caption" color="text.secondary">{u.email || "—"}</Typography></TableCell><TableCell>{u.username || "—"}</TableCell><TableCell>{u.is_admin ? <Chip size="small" label="管理员" color="primary" /> : "普通用户"}</TableCell><TableCell><Chip size="small" label={u.status === "ACTIVE" ? "正常" : "已禁用"} color={u.status === "ACTIVE" ? "success" : "default"} /></TableCell><TableCell onClick={e => e.stopPropagation()}><Button size="small" disabled={protectedAccount} color={u.status === "ACTIVE" ? "error" : "primary"} onClick={() => void toggle(u)}>{protectedAccount ? "不可操作" : u.status === "ACTIVE" ? "禁用" : "启用"}</Button></TableCell></TableRow>; })}</TableBody></Table></CardContent></Card><Dialog open={Boolean(detail)} onClose={() => setDetail(null)} fullWidth maxWidth="sm"><DialogTitle>用户详情</DialogTitle><DialogContent dividers>{detail && <Table size="small"><TableBody><TableRow><TableCell>姓名</TableCell><TableCell>{detail.display_name}</TableCell></TableRow><TableRow><TableCell>飞书账号 ID</TableCell><TableCell>{detail.username || "—"}</TableCell></TableRow><TableRow><TableCell>邮箱</TableCell><TableCell>{detail.email || "—"}</TableCell></TableRow><TableRow><TableCell>角色</TableCell><TableCell>{detail.is_admin ? "管理员" : "普通用户"}</TableCell></TableRow><TableRow><TableCell>状态</TableCell><TableCell>{detail.status === "ACTIVE" ? "正常" : "已禁用"}</TableCell></TableRow><TableRow><TableCell>账号来源</TableCell><TableCell>{detail.created_source}</TableCell></TableRow><TableRow><TableCell>飞书绑定</TableCell><TableCell>{detail.feishu.bound ? "已绑定" : "未绑定"}</TableCell></TableRow><TableRow><TableCell>绑定时间</TableCell><TableCell>{detail.feishu.bound_at ? new Date(detail.feishu.bound_at).toLocaleString() : "—"}</TableCell></TableRow><TableRow><TableCell>创建时间</TableCell><TableCell>{new Date(detail.created_at).toLocaleString()}</TableCell></TableRow></TableBody></Table>}</DialogContent><DialogActions><Button onClick={() => setDetail(null)}>关闭</Button></DialogActions></Dialog></>;
}
